# Generated by Django 4.1.6 on 2024-01-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='account',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='username',
        ),
    ]
