# Generated by Django 4.2.7 on 2024-02-08 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_account_passwordresets_account_id_and_more'),
        ('message', '0002_rename_account_messages_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messagereport', to='account.webusers')),
            ],
            options={
                'db_table': 'MessageReport',
            },
        ),
    ]
