# Generated by Django 4.2.7 on 2024-01-10 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webusers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateTimeField()),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'webusers',
            },
        ),
        migrations.CreateModel(
            name='RegisterVerify',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('verify_token', models.CharField(max_length=255)),
                ('token_expiration', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.webusers')),
            ],
            options={
                'db_table': 'register_verify',
            },
        ),
        migrations.CreateModel(
            name='PasswordResets',
            fields=[
                ('reset_id', models.AutoField(primary_key=True, serialize=False)),
                ('reset_token', models.CharField(max_length=255)),
                ('token_expiration', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('was_used', models.IntegerField(default='0')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.webusers')),
            ],
            options={
                'db_table': 'password_resets',
            },
        ),
    ]
