# Generated by Django 4.2.7 on 2024-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webusers',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='webusers',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
