# Generated by Django 4.2.7 on 2024-01-12 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_webusers_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordresets',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='registerverify',
            old_name='account',
            new_name='account_id',
        ),
    ]
