# Generated by Django 5.0.2 on 2024-02-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_rename_account_passwordresets_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAccountLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lineid', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('nonce', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lineaccountlink', to='account.webusers')),
            ],
            options={
                'db_table': 'LineAccountLink',
            },
        ),
    ]
