# Generated by Django 4.2.8 on 2024-02-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineBot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineaccountlink',
            name='token',
        ),
    ]
