# Generated by Django 4.1.7 on 2024-01-29 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user_id',
            new_name='accont',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='id',
            new_name='shop',
        ),
    ]
