# Generated by Django 4.1.7 on 2024-01-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0004_rename_user_id_comments_accont_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='accont',
            new_name='account',
        ),
    ]
