# Generated by Django 4.1.7 on 2024-01-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0005_rename_accont_comments_account'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comment',
        ),
    ]
