# Generated by Django 4.1.7 on 2024-01-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0006_alter_comments_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comments',
            table='comments',
        ),
    ]
