# Generated by Django 4.1.7 on 2024-01-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0007_alter_comments_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
