# Generated by Django 4.1.7 on 2024-01-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_account_passwordresets_account_id_and_more'),
        ('RecommenderSystem', '0008_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.webusers')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecommenderSystem.shopsdata')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
    ]
