# Generated by Django 4.2.8 on 2024-02-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0009_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsdata',
            name='shopType',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.CreateModel(
            name='ShopsKeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyWords', models.CharField(max_length=300, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecommenderSystem.shopsdata')),
            ],
            options={
                'db_table': 'shopsKeyWords',
            },
        ),
    ]
