# Generated by Django 4.2.8 on 2024-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0010_shopsdata_shoptype_shopskeywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopskeywords',
            name='contentKeyWords',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
