# Generated by Django 4.2.8 on 2024-02-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0013_shopskeywords_similarityscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopskeywords',
            name='similarityShop',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopskeywords',
            name='similarityScore',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
