# Generated by Django 4.1.7 on 2024-02-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0014_shopskeywords_similarityshop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
