# Generated by Django 4.2.8 on 2024-02-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommenderSystem', '0015_delete_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopskeywords',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
